version: "3.8"
networks:
  cas-net:
    driver: bridge

services:
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    networks:
      - cas-net
    restart: unless-stopped
  cas_brain:
    image: tobsa/cas_brain:master
    volumes:
      - /opt/cas/config.json:/opt/config.json:ro
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - cas-net
    restart: unless-stopped
  cas_redis2http:
    image: tobsa/cas_redis2http:master
    volumes:
      - /opt/cas/config.json:/opt/config.json:ro
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - cas-net
    restart: unless-stopped
  cas_multimon-ng2redis:
    image: tobsa/cas_multimon-ng2redis:master
    volumes:
      - /var/run/pulse:/tmp/pulse
      - /opt/cas/config.json:/opt/config.json:ro
    environment:
      REDIS_HOST: redis
      PULSE_SERVER: "unix:/tmp/pulse/native"
    depends_on:
      - redis
    networks:
      - cas-net
    restart: unless-stopped
  cas_redis2LEDs:
    image: tobsa/cas_redis2leds:master
    volumes:
      - /opt/cas/config.json:/opt/config.json:ro
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - cas-net
    restart: unless-stopped
    devices:
      - "/dev/gpiomem"
  cas_redis2local:
    image: tobsa/cas_redis2local:master
    volumes:
      - /opt/cas/config.json:/opt/config.json:ro
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    networks:
      - cas-net
    restart: unless-stopped
    devices:
      - "/dev/gpiomem"
